In [1]:
import numpy as np

In [2]:
def activate(x):
    return 1/(1+np.exp(-x))

def activateDx(x):
    return x*(1-x)

In [3]:
X = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [1,1,1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [4]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [5]:
y

array([[0],
       [1],
       [1],
       [0]])

In [6]:
np.random.seed(1)
syn0 = 2*np.random.random((3,4)) - 1 
syn1 = 2*np.random.random((4,1)) - 1

In [7]:
print('syn0:\n', syn0)
print('syn1:\n', syn1)

syn0:
 [[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
syn1:
 [[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


In [8]:
epochs = 10_000
print_every = 1_000

In [9]:
for j in range(epochs):
    l0 = X
    l1 = activate(np.dot(l0, syn0))
    l2 = activate(np.dot(l1, syn1))

    # what is a difference between what we've got and expected
    l2_error = y - l2

    if (j % print_every) == 0:
        print('Error:', np.mean(np.abs(l2_error)))

    # determine delta to update weights
    l2_delta = l2_error * activateDx(l2)

    # determine how prev layer participated in final error
    l1_error = l2_delta.dot(syn1.T)

    # determine delta to update weights of the first layer
    l1_delta = l1_error * activateDx(l1)

    # update weights
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error: 0.49641003190272537
Error: 0.042984647810726216
Error: 0.024121949891468493
Error: 0.018121400645678864
Error: 0.014993830283221644
Error: 0.013018434775309312
Error: 0.011633855795037226
Error: 0.010597596833851579
Error: 0.009786192568908622
Error: 0.009129524184004872


In [10]:
def test(x):
    y = activate(np.dot(x, syn0))
    y = activate(np.dot(y, syn1))    
    return 1 if y[0] > 0.5 else 0, y[0]

In [11]:
test(np.array(np.array([0,0,1])))

(0, 0.007021724442763223)

In [12]:
test(np.array(np.array([0,1,1])))

(1, 0.991010054367377)